apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "k6-metrics"
    timeField: "Time"
    jsonData:
      esVersion: 8
      timeField: "Time"
      maxConcurrentShardRequests: 5
    editable: true

